default_platform(:ios)

platform :ios do
  desc "Build the iOS app"
  lane :build do
    match(
      type: "adhoc", 
      git_url: "https://github.com/xiihaiqal/tethering.git" # Replace with your actual Git repository URL
    )
    gym(scheme: "Tethering") # Replace with your actual scheme name
  end
end
