default_platform(:ios)

platform :ios do
  desc "Build the iOS app"
  lane :build do
    match(type: "adhoc") # or "development" depending on your needs
    gym(scheme: "Tethering") # Replace with your actual scheme name
  end
end
