name: Build IPA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ipa:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build IPA
      run: |
        xcodebuild clean archive \
          -project tethering.xcodeproj \
          -scheme TetheringApp \
          -configuration Release \
          -archivePath $PWD/build/TetheringApp.xcarchive \
          -sdk iphoneos \
          IPHONEOS_DEPLOYMENT_TARGET=12.0

        xcodebuild -exportArchive \
          -archivePath $PWD/build/TetheringApp.xcarchive \
          -exportPath $PWD/build \
          -exportOptionsPlist ExportOptions.plist

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: tethering.ipa
        path: build/TetheringApp.ipa
